language: go

go:
  - "1.16.x"

# Don't email me the results of the test runs.
notifications:
  email: false

script:
- go test -v -race ./...  # Run all the tests with the race detector enabled
- go build ./cmd/jira/...
